[postgres_servers]
db01 ansible_host=192.168.122.33 ansible_user=root
db02 ansible_host=192.168.122.34 ansible_user=root
db03 ansible_host=192.168.122.49 ansible_user=root


[postgres_servers:vars]
ansible_python_interpreter=/usr/bin/python3
